
package hotelreservationservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HotelReservationService", targetNamespace = "http://HotelReservationServices", wsdlLocation = "file:/C:/Users/emil/Documents/NetBeansProjects/HotelReservationServicesSOAP/src/java/ws/HotelReservation.wsdl")
public class HotelReservationService
    extends Service
{

    private final static URL HOTELRESERVATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELRESERVATIONSERVICE_EXCEPTION;
    private final static QName HOTELRESERVATIONSERVICE_QNAME = new QName("http://HotelReservationServices", "HotelReservationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/emil/Documents/NetBeansProjects/HotelReservationServicesSOAP/src/java/ws/HotelReservation.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELRESERVATIONSERVICE_WSDL_LOCATION = url;
        HOTELRESERVATIONSERVICE_EXCEPTION = e;
    }

    public HotelReservationService() {
        super(__getWsdlLocation(), HOTELRESERVATIONSERVICE_QNAME);
    }

    public HotelReservationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns HotelReservationServices
     */
    @WebEndpoint(name = "HotelReservationServicesBindingPort")
    public HotelReservationServices getHotelReservationServicesBindingPort() {
        return super.getPort(new QName("http://HotelReservationServices", "HotelReservationServicesBindingPort"), HotelReservationServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelReservationServices
     */
    @WebEndpoint(name = "HotelReservationServicesBindingPort")
    public HotelReservationServices getHotelReservationServicesBindingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://HotelReservationServices", "HotelReservationServicesBindingPort"), HotelReservationServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELRESERVATIONSERVICE_EXCEPTION!= null) {
            throw HOTELRESERVATIONSERVICE_EXCEPTION;
        }
        return HOTELRESERVATIONSERVICE_WSDL_LOCATION;
    }

}
