
package dtu.ws.group8.lameduck.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LameDuckWSDLPortType", targetNamespace = "http://lameduck.group8.ws.dtu")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LameDuckWSDLPortType {


    /**
     * 
     * @param input
     * @return
     *     returns dtu.ws.group8.lameduck.client.FlightInfoListType
     */
    @WebMethod
    @WebResult(name = "output", partName = "output")
    public FlightInfoListType getFlights(
        @WebParam(name = "input", partName = "input")
        GetFlightRequestType input);

    /**
     * 
     * @param input
     * @return
     *     returns boolean
     * @throws BookFlightFault
     */
    @WebMethod
    @WebResult(name = "output", partName = "output")
    public boolean bookFlight(
        @WebParam(name = "input", partName = "input")
        BookFlightRequestType input)
        throws BookFlightFault
    ;

    /**
     * 
     * @param input
     * @return
     *     returns boolean
     * @throws CancelFlightFault
     */
    @WebMethod
    @WebResult(name = "output", partName = "output")
    public boolean cancelFlight(
        @WebParam(name = "input", partName = "input")
        CancelFlightRequestType input)
        throws CancelFlightFault
    ;

}
